//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterpies.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.PatientReviews = new HashSet<PatientReview>();
        }
    
        public int AppointmentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> patientAge { get; set; }
        public Nullable<bool> patientgender { get; set; }
        public string city { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string aspuserid { get; set; }
        [DisplayName("Appointment Time")]
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> Timeslotsid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReview> PatientReviews { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Device Device { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
