//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterpies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string comment1 { get; set; }
        public string aspuser { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> id_blog { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
