//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterpies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int DeviceID { get; set; }
        public string DeviceName { get; set; }
        public string Description { get; set; }
        public string Devicebackground { get; set; }
        public string DeviceImg2 { get; set; }
        public string DeviceImg3 { get; set; }
        public string step1 { get; set; }
        public string step2 { get; set; }
        public string step3 { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
