//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterpies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientReview
    {
        public int ReviewID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string ReviewText { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Userid { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
