//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterpies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int iduser { get; set; }
        public string userName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string aspuserid { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
